export type Certificate = {
  id: string;
  image: string;
  width: number;
  height: number;
  kind: "certificate" | "trophy";
  title: string;
  issuer: string;
  project: string;
  year: string;
  category: "safety" | "execution" | "recognition";
  alt: string;
};

export const certificatesIntro =
  "Recognised by leading EPC contractors and cleanroom specialists for safety leadership, execution quality, and project delivery across industrial campuses nationwide.";

export const certificates: Certificate[] = [
  {
    id: "daikin-safety-2024",
    image: "/images/certificates/IMG_3809.jpg",
    width: 4508,
    height: 3381,
    kind: "certificate",
    title: "Certificate of Appreciation",
    issuer: "Takenaka",
    project: "Daikin New R&D Centre (Neemrana)",
    year: "2023–24",
    category: "safety",
    alt: "Takenaka Certificate of Appreciation to Greenwave for teamwork at Daikin New R&D Centre Project on Indian National Safety Day 2024",
  },
  {
    id: "takenaka-hsse-2025",
    image: "/images/certificates/IMG_3821.jpg",
    width: 3950,
    height: 5267,
    kind: "trophy",
    title: "HSSE Award — Silver & Bronze Performer",
    issuer: "Takenaka India",
    project: "National Safety Day recognition",
    year: "2025",
    category: "safety",
    alt: "Takenaka India HSSE Award 2025 Silver and Bronze Performer plaques to Greenwave Engineering on National Safety Day 2026",
  },
  {
    id: "pepsico-silver-2022",
    image: "/images/certificates/IMG_3814.jpg",
    width: 3764,
    height: 5018,
    kind: "certificate",
    title: "Silver Prize — Outstanding Effort",
    issuer: "Takenaka",
    project: "PepsiCo UP Greenfield",
    year: "2020–21",
    category: "execution",
    alt: "Takenaka Silver Prize Certificate of Recognition to Green Wave for PepsiCo UP Greenfield Project",
  },
  {
    id: "takenaka-qhse-trophies",
    image: "/images/certificates/IMG_3820.jpg",
    width: 4032,
    height: 3024,
    kind: "trophy",
    title: "QHSE & Safety Performance Trophies",
    issuer: "Takenaka India",
    project: "Best performance 2019–2024",
    year: "2019–24",
    category: "safety",
    alt: "Takenaka India QHSE and Safety Appreciation glass trophies to Green Wave for best performance across 2019–2020, 2020–2021, and 2023–2024",
  },
  {
    id: "oji-packaging",
    image: "/images/certificates/IMG_3813.jpg",
    width: 3544,
    height: 4725,
    kind: "certificate",
    title: "Certificate of Appreciation",
    issuer: "Takenaka",
    project: "Oji India Packaging Sricity",
    year: "Recognition",
    category: "execution",
    alt: "Takenaka Certificate of Appreciation to Greenwave Engineering for Oji India Packaging Sricity New Factory Project",
  },
  {
    id: "iclean-appreciation",
    image: "/images/certificates/IMG_3819.jpg",
    width: 5131,
    height: 3848,
    kind: "certificate",
    title: "Certificate of Appreciation",
    issuer: "iClean / Takasago",
    project: "Outstanding accomplishments",
    year: "Recognition",
    category: "recognition",
    alt: "Integrated Cleanroom Technologies Certificate of Appreciation to Green Wave for outstanding accomplishments",
  },
  {
    id: "takenaka-kaizen-appreciation",
    image: "/images/certificates/IMG_3823.jpg",
    width: 4032,
    height: 3024,
    kind: "trophy",
    title: "Appreciation Award",
    issuer: "Takenaka India",
    project: "Kaizen & continuous improvement",
    year: "Recognition",
    category: "recognition",
    alt: "Takenaka India circular glass appreciation award to Green Wave for commitment and dedicated service with Kaizen spirit",
  },
  {
    id: "yanmar-silver-2021",
    image: "/images/certificates/IMG_3811.jpg",
    width: 3468,
    height: 4628,
    kind: "certificate",
    title: "Silver Prize — Outstanding Effort",
    issuer: "Takenaka",
    project: "Yanmar India Engine Factory",
    year: "2019–20",
    category: "execution",
    alt: "Takenaka Silver Prize Certificate of Recognition to Vikram Mehra of GreenWave for Yanmar India Engine Factory",
  },
  {
    id: "takenaka-best-contractor-oji",
    image: "/images/certificates/IMG_3825.jpg",
    width: 5712,
    height: 4284,
    kind: "trophy",
    title: "Best Contractor Award",
    issuer: "Takenaka & Daiichi Jitsugyo",
    project: "Oji India Packaging & HMSI-Rupan",
    year: "2023–24",
    category: "execution",
    alt: "Takenaka Best Contractor award for Oji India Packaging Sri City and Daiichi Jitsugyo HMSI-Rupan contribution trophy to Greenwave",
  },
  {
    id: "iclean-safety",
    image: "/images/certificates/IMG_3818.jpg",
    width: 5018,
    height: 3764,
    kind: "certificate",
    title: "Certificate of Achievement",
    issuer: "iClean / Takasago",
    project: "Safety culture commitment",
    year: "Award",
    category: "safety",
    alt: "iClean Takasago Certificate of Achievement to Green Wave Team for safety commitment and awareness",
  },
  {
    id: "takenaka-15th-anniversary",
    image: "/images/certificates/IMG_3822.jpg",
    width: 3562,
    height: 4753,
    kind: "trophy",
    title: "1st Position — 15th Anniversary",
    issuer: "Takenaka India",
    project: "Future-ready & sustainable projects",
    year: "Anniversary",
    category: "recognition",
    alt: "Takenaka India 15th Anniversary award — 1st Position to Greenwave Engineering for support to TKIN sustainable projects",
  },
  {
    id: "hmsi-rupantar-2022",
    image: "/images/certificates/IMG_3824.jpg",
    width: 3923,
    height: 2942,
    kind: "certificate",
    title: "Certificate of Appreciation",
    issuer: "Daiichi Jitsugyo India",
    project: "HMSI Rupantar 2022",
    year: "2022",
    category: "execution",
    alt: "Daiichi Jitsugyo Certificate of Appreciation to Greenwave Engineering for HMSI Rupantar 2022 Project",
  },
  {
    id: "ijl-safety-2020",
    image: "/images/certificates/IMG_3812.jpg",
    width: 4313,
    height: 3235,
    kind: "certificate",
    title: "Safety Appreciation",
    issuer: "Takenaka",
    project: "India Japan Lighting",
    year: "2019–20",
    category: "safety",
    alt: "Takenaka Certificate of Safety Appreciation to Greenwave for India Japan Lighting Project on National Safety Day 2020",
  },
];
