export type ClientLogo = {
  src: string;
  name: string;
};

const PAGE5_LOGO_FILES = [
  "page5_img0.jpeg",
  "page5_img1.jpeg",
  "page5_img2.jpeg",
  "page5_img3.jpeg",
  "page5_img4.jpeg",
  "page5_img5.jpeg",
  "page5_img6.png",
  "page5_img7.jpeg",
  "page5_img8.jpeg",
  "page5_img9.jpeg",
  "page5_img10.jpeg",
  "page5_img11.jpeg",
  "page5_img12.jpeg",
  "page5_img13.jpeg",
  "page5_img14.jpeg",
  "page5_img15.jpeg",
  "page5_img16.jpeg",
  "page5_img17.png",
  "page5_img18.jpeg",
  "page5_img19.jpeg",
  "page5_img20.jpeg",
  "page5_img21.jpeg",
  "page5_img22.jpeg",
  "page5_img23.jpeg",
  "page5_img24.png",
  "page5_img25.jpeg",
  "page5_img26.jpeg",
  "page5_img27.jpeg",
  "page5_img28.jpeg",
  "page5_img29.jpeg",
  "page5_img30.png",
  "page5_img31.png",
  "page5_img32.jpeg",
  "page5_img33.jpeg",
  "page5_img34.jpeg",
  "page5_img35.jpeg",
  "page5_img36.jpeg",
  "page5_img37.jpeg",
  "page5_img38.png",
  "page5_img39.jpeg",
  "page5_img40.jpeg",
  "page5_img41.png",
  "page5_img42.jpeg",
  "page5_img43.jpeg",
  "page5_img44.jpeg",
  "page5_img45.jpeg",
  "page5_img46.jpeg",
  "page5_img47.jpeg",
  "page5_img48.jpeg",
  "page5_img49.jpeg",
  "page5_img50.jpeg",
  "page5_img51.jpeg",
  "page5_img52.jpeg",
  "page5_img53.jpeg",
  "page5_img54.jpeg",
] as const;

const LOGO_NAMES: Partial<Record<(typeof PAGE5_LOGO_FILES)[number], string>> = {
  "page5_img0.jpeg": "Unicharm",
  "page5_img1.jpeg": "Anchor by Panasonic",
  "page5_img2.jpeg": "Daikin",
  "page5_img3.jpeg": "LG",
  "page5_img4.jpeg": "OJI Paper",
  "page5_img5.jpeg": "Yanmar",
  "page5_img6.png": "Mitsubishi Electric",
  "page5_img7.jpeg": "Brother",
  "page5_img8.jpeg": "Mitsubishi Electric",
  "page5_img9.jpeg": "IMAX",
  "page5_img10.jpeg": "TS TECH",
  "page5_img12.jpeg": "Nippon Auto Parts",
  "page5_img14.jpeg": "Maruti Suzuki",
  "page5_img15.jpeg": "Futaba Industrial",
  "page5_img18.jpeg": "Lewis Berger",
  "page5_img24.png": "Blue Star",
  "page5_img26.jpeg": "Mitsubishi Electric",
  "page5_img30.png": "YKK",
  "page5_img33.jpeg": "PepsiCo",
  "page5_img42.jpeg": "E & H",
  "page5_img47.jpeg": "Amara Raja",
  "page5_img50.jpeg": "ATL",
};

export const clientLogos: ClientLogo[] = PAGE5_LOGO_FILES.map((file) => ({
  src: `/images/pdf-fitz/${file}`,
  name: LOGO_NAMES[file] ?? "Industrial client",
}));

export const clientLogoRows = [
  clientLogos.slice(0, Math.ceil(clientLogos.length / 2)),
  clientLogos.slice(Math.ceil(clientLogos.length / 2)),
] as const;
