// Auto-generated by scripts/import_projects.py — do not edit manually.

export const SERVICE_TITLES = [
  "Air conditioning",
  "Ducting",
  "Insulation",
  "Ventilation",
  "Fire fighting",
  "Chilled water piping",
  "Utility piping",
  "PEX piping",
  "Steam piping",
  "Refrigeration",
  "Electrical",
  "Gas piping",
  "Chemical piping",
  "Dust collection",
  "Plumbing",
  "Civil and interioirs",
  "DG Chimey",
  "Machine setup & hookup",
  "Turnkey AWC lab"
] as const;

export const INDUSTRY_TITLES = [
  "R&D",
  "Automotive",
  "Air conditioning",
  "Lithium ion battery (Dry room)",
  "office",
  "Clean room",
  "FMCG",
  "Food",
  "Pharmaceutical",
  "Mobile phones",
  "Other"
] as const;

export type ServiceTitle = (typeof SERVICE_TITLES)[number];
export type IndustryTitle = (typeof INDUSTRY_TITLES)[number];
