// Auto-generated by scripts/import_projects.py — do not edit manually.
export type DistributionSegment = {
  id: string;
  label: string;
  percentage: number;
  color: string;
};

export const portfolioDistributionIntro =
  "Execution portfolio value derived from the FY25–26 project register — using the exact service and industry columns defined in the spreadsheet.";

export const portfolioDistributionPeriod = "FY25–26";

export const serviceSegments: DistributionSegment[] = [
  {
    "id": "insulation",
    "label": "Insulation",
    "percentage": 13.7,
    "color": "#1a4731"
  },
  {
    "id": "ducting",
    "label": "Ducting",
    "percentage": 13.1,
    "color": "#5ba4cf"
  },
  {
    "id": "ventilation",
    "label": "Ventilation",
    "percentage": 12.4,
    "color": "#2f8f8f"
  },
  {
    "id": "utility-piping",
    "label": "Utility piping",
    "percentage": 11.0,
    "color": "#4a6fa5"
  },
  {
    "id": "chilled-water-piping",
    "label": "Chilled water piping",
    "percentage": 9.9,
    "color": "#8b2e2e"
  },
  {
    "id": "fire-fighting",
    "label": "Fire fighting",
    "percentage": 9.8,
    "color": "#d64545"
  },
  {
    "id": "steam-piping",
    "label": "Steam piping",
    "percentage": 7.3,
    "color": "#6b4c8a"
  },
  {
    "id": "air-conditioning",
    "label": "Air conditioning",
    "percentage": 4.8,
    "color": "#3d4f7c"
  },
  {
    "id": "gas-piping",
    "label": "Gas piping",
    "percentage": 3.5,
    "color": "#2d6a4f"
  },
  {
    "id": "electrical",
    "label": "Electrical",
    "percentage": 3.3,
    "color": "#457b9d"
  },
  {
    "id": "machine-setup-hookup",
    "label": "Machine setup & hookup",
    "percentage": 3.1,
    "color": "#6d597a"
  },
  {
    "id": "dg-chimey",
    "label": "DG Chimey",
    "percentage": 2.4,
    "color": "#bc6c25"
  },
  {
    "id": "dust-collection",
    "label": "Dust collection",
    "percentage": 2.0,
    "color": "#1a4731"
  },
  {
    "id": "plumbing",
    "label": "Plumbing",
    "percentage": 1.7,
    "color": "#5ba4cf"
  },
  {
    "id": "civil-and-interioirs",
    "label": "Civil and interioirs",
    "percentage": 0.7,
    "color": "#2f8f8f"
  },
  {
    "id": "refrigeration",
    "label": "Refrigeration",
    "percentage": 0.5,
    "color": "#4a6fa5"
  },
  {
    "id": "turnkey-awc-lab",
    "label": "Turnkey AWC lab",
    "percentage": 0.4,
    "color": "#8b2e2e"
  },
  {
    "id": "chemical-piping",
    "label": "Chemical piping",
    "percentage": 0.3,
    "color": "#d64545"
  },
  {
    "id": "pex-piping",
    "label": "PEX piping",
    "percentage": 0.1,
    "color": "#6b4c8a"
  }
];

export const industrySegments: DistributionSegment[] = [
  {
    "id": "lithium-ion-battery-dry-room",
    "label": "Lithium ion battery (Dry room)",
    "percentage": 23.9,
    "color": "#5ba4cf"
  },
  {
    "id": "automotive",
    "label": "Automotive",
    "percentage": 22.9,
    "color": "#d64545"
  },
  {
    "id": "clean-room",
    "label": "Clean room",
    "percentage": 16.0,
    "color": "#2f8f8f"
  },
  {
    "id": "air-conditioning",
    "label": "Air conditioning",
    "percentage": 14.9,
    "color": "#1a4731"
  },
  {
    "id": "other",
    "label": "Other",
    "percentage": 11.1,
    "color": "#4a6fa5"
  },
  {
    "id": "fmcg",
    "label": "FMCG",
    "percentage": 5.5,
    "color": "#6b4c8a"
  },
  {
    "id": "r-d",
    "label": "R&D",
    "percentage": 3.4,
    "color": "#3d4f7c"
  },
  {
    "id": "food",
    "label": "Food",
    "percentage": 1.2,
    "color": "#8b2e2e"
  },
  {
    "id": "mobile-phones",
    "label": "Mobile phones",
    "percentage": 0.5,
    "color": "#457b9d"
  },
  {
    "id": "pharmaceutical",
    "label": "Pharmaceutical",
    "percentage": 0.3,
    "color": "#bc6c25"
  },
  {
    "id": "office",
    "label": "office",
    "percentage": 0.3,
    "color": "#2d6a4f"
  }
];
