// Auto-generated by scripts/import_projects.py — do not edit manually.
import type { Project } from "@/content/taxonomy";

export const projects: Project[] = [
  {
    "id": "unicharm",
    "name": "Unicharm",
    "city": "Sri City",
    "state": "Andhra Pradesh",
    "location": "Sri City, Andhra Pradesh",
    "value": "65 M INR",
    "valueM": 65.0,
    "status": "Completed",
    "services": [
      "Air conditioning",
      "DG Chimey",
      "Ducting",
      "Dust collection",
      "Insulation",
      "Machine setup & hookup",
      "Ventilation"
    ],
    "industries": [
      "FMCG"
    ],
    "scopeServices": [],
    "image": "/images/projects/web/unicharm.png",
    "featured": false,
    "epcPartner": "Maeda corporation",
    "startYear": "2014",
    "endYear": "2016"
  },
  {
    "id": "panasonic-life-solutions",
    "name": "Panasonic life solutions",
    "city": "Sri City",
    "state": "Andhra Pradesh",
    "location": "Sri City, Andhra Pradesh",
    "value": "72 M INR",
    "valueM": 72.0,
    "status": "Completed",
    "services": [
      "Fire fighting",
      "Utility piping"
    ],
    "industries": [
      "FMCG"
    ],
    "scopeServices": [],
    "image": "/images/projects/clean/panasonic-life-solutions.jpg",
    "featured": false,
    "epcPartner": "Takenaka India",
    "startYear": "2021",
    "endYear": "2022"
  },
  {
    "id": "oji-paper",
    "name": "OJI paper",
    "city": "Sri City",
    "state": "Andhra Pradesh",
    "location": "Sri City, Andhra Pradesh",
    "value": "180 M INR",
    "valueM": 180.0,
    "status": "Completed",
    "services": [
      "DG Chimey",
      "Electrical",
      "Fire fighting",
      "Machine setup & hookup",
      "Steam piping",
      "Utility piping"
    ],
    "industries": [
      "Other"
    ],
    "scopeServices": [],
    "image": "/images/projects/clean/oji-paper.jpg",
    "featured": false,
    "epcPartner": "Takenaka India",
    "startYear": "2023",
    "endYear": "2024"
  },
  {
    "id": "daikin-device-factory",
    "name": "Daikin Device factory",
    "city": "Sri City",
    "state": "Andhra Pradesh",
    "location": "Sri City, Andhra Pradesh",
    "value": "170 M INR",
    "valueM": 170.0,
    "status": "Completed",
    "services": [
      "Air conditioning",
      "Chilled water piping",
      "DG Chimey",
      "Ducting",
      "Electrical",
      "Fire fighting",
      "Gas piping",
      "Insulation",
      "Machine setup & hookup",
      "Utility piping",
      "Ventilation"
    ],
    "industries": [
      "Air conditioning"
    ],
    "scopeServices": [],
    "image": "/images/projects/clean/daikin-device-factory.jpg",
    "featured": false,
    "epcPartner": "Takenaka India",
    "startYear": "2025",
    "endYear": "2026"
  },
  {
    "id": "daikin-jv",
    "name": "Daikin JV",
    "city": "Sri City",
    "state": "Andhra Pradesh",
    "location": "Sri City, Andhra Pradesh",
    "value": "250 M INR",
    "valueM": 250.0,
    "status": "Ongoing",
    "services": [
      "Air conditioning",
      "Chilled water piping",
      "DG Chimey",
      "Ducting",
      "Electrical",
      "Fire fighting",
      "Gas piping",
      "Insulation",
      "Utility piping"
    ],
    "industries": [
      "Air conditioning"
    ],
    "scopeServices": [],
    "image": "/images/projects/clean/daikin-jv.jpg",
    "featured": true,
    "epcPartner": "Takenaka India",
    "startYear": "Ongoing"
  },
  {
    "id": "bluestar",
    "name": "Bluestar",
    "city": "Sri City",
    "state": "Andhra Pradesh",
    "location": "Sri City, Andhra Pradesh",
    "value": "40 M INR",
    "valueM": 40.0,
    "status": "Completed",
    "services": [
      "Chemical piping",
      "Gas piping",
      "Machine setup & hookup",
      "Utility piping"
    ],
    "industries": [
      "Air conditioning"
    ],
    "scopeServices": [],
    "image": "/images/projects/clean/bluestar.jpg",
    "featured": false,
    "epcPartner": "Bluestar",
    "startYear": "2022",
    "endYear": "2024"
  },
  {
    "id": "lg",
    "name": "LG",
    "city": "Sri City",
    "state": "Andhra Pradesh",
    "location": "Sri City, Andhra Pradesh",
    "value": "93 M INR",
    "valueM": 93.0,
    "status": "Ongoing",
    "services": [
      "Gas piping",
      "Insulation",
      "Steam piping",
      "Utility piping"
    ],
    "industries": [
      "Air conditioning",
      "FMCG"
    ],
    "scopeServices": [],
    "image": "/images/projects/clean/lg.jpg",
    "featured": false,
    "epcPartner": "Ck Solutions",
    "startYear": "Ongoing"
  },
  {
    "id": "panasonic-life-appliances",
    "name": "Panasonic life appliances",
    "city": "Ponneri",
    "state": "Tamil Nadu",
    "location": "Ponneri, Tamil Nadu",
    "value": "40 M INR",
    "valueM": 40.0,
    "status": "Completed",
    "services": [
      "Electrical",
      "Fire fighting"
    ],
    "industries": [
      "FMCG"
    ],
    "scopeServices": [],
    "image": "/images/projects/clean/panasonic-life-appliances.jpg",
    "featured": false,
    "epcPartner": "Panasonic life appliances",
    "startYear": "2022",
    "endYear": "2024"
  },
  {
    "id": "yanmar",
    "name": "Yanmar",
    "city": "Ponneri",
    "state": "Tamil Nadu",
    "location": "Ponneri, Tamil Nadu",
    "value": "30 M INR",
    "valueM": 30.0,
    "status": "Completed",
    "services": [
      "Steam piping",
      "Utility piping"
    ],
    "industries": [
      "Automotive"
    ],
    "scopeServices": [],
    "image": "/images/projects/clean/yanmar.jpg",
    "featured": false,
    "epcPartner": "Takenaka India",
    "startYear": "2019",
    "endYear": "2020"
  },
  {
    "id": "yanmar-2",
    "name": "Yanmar",
    "city": "Ponneri",
    "state": "Tamil Nadu",
    "location": "Ponneri, Tamil Nadu",
    "value": "6 M INR",
    "valueM": 6.0,
    "status": "Completed",
    "services": [
      "Electrical",
      "Fire fighting"
    ],
    "industries": [
      "Automotive"
    ],
    "scopeServices": [],
    "image": "/images/projects/clean/yanmar-2.jpg",
    "featured": false,
    "epcPartner": "Takenaka India",
    "startYear": "2022",
    "endYear": "2022"
  },
  {
    "id": "track-design-india",
    "name": "Track design India",
    "city": "Ponneri",
    "state": "Tamil Nadu",
    "location": "Ponneri, Tamil Nadu",
    "value": "35 M INR",
    "valueM": 35.0,
    "status": "Completed",
    "services": [
      "Electrical",
      "Fire fighting",
      "Utility piping"
    ],
    "industries": [
      "Other"
    ],
    "scopeServices": [],
    "image": "/images/projects/clean/track-design-india.jpg",
    "featured": false,
    "epcPartner": "Takenaka India",
    "startYear": "2022",
    "endYear": "2023"
  },
  {
    "id": "mitsubishi-electric-ac",
    "name": "Mitsubishi Electric - AC",
    "city": "Ponneri",
    "state": "Tamil Nadu",
    "location": "Ponneri, Tamil Nadu",
    "value": "55 M INR",
    "valueM": 55.0,
    "status": "Completed",
    "services": [
      "Fire fighting"
    ],
    "industries": [
      "Air conditioning"
    ],
    "scopeServices": [],
    "image": "/images/projects/clean/mitsubishi-electric-ac.jpg",
    "featured": false,
    "epcPartner": "Shimizu corporation",
    "startYear": "2024",
    "endYear": "2025"
  },
  {
    "id": "mitsubishi-electric-ac-2",
    "name": "Mitsubishi Electric - AC",
    "city": "Ponneri",
    "state": "Tamil Nadu",
    "location": "Ponneri, Tamil Nadu",
    "value": "75 M INR",
    "valueM": 75.0,
    "status": "Completed",
    "services": [
      "Ducting",
      "Electrical",
      "Gas piping",
      "Insulation",
      "Machine setup & hookup",
      "Utility piping",
      "Ventilation"
    ],
    "industries": [
      "Air conditioning"
    ],
    "scopeServices": [],
    "image": "/images/projects/clean/mitsubishi-electric-ac-2.jpg",
    "featured": false,
    "epcPartner": "DJK",
    "startYear": "2025",
    "endYear": "2025"
  },
  {
    "id": "mitsubishi-electric-ac-3",
    "name": "Mitsubishi Electric - AC",
    "city": "Ponneri",
    "state": "Tamil Nadu",
    "location": "Ponneri, Tamil Nadu",
    "value": "15 M INR",
    "valueM": 15.0,
    "status": "Completed",
    "services": [
      "Ducting",
      "Insulation",
      "Machine setup & hookup",
      "Ventilation"
    ],
    "industries": [
      "Air conditioning"
    ],
    "scopeServices": [],
    "image": "/images/projects/clean/mitsubishi-electric-ac-3.jpg",
    "featured": false,
    "epcPartner": "TTIPL",
    "startYear": "2025",
    "endYear": "2025"
  },
  {
    "id": "hitachi-ams",
    "name": "Hitachi AMS",
    "city": "Chennai",
    "state": "Tamil Nadu",
    "location": "Chennai, Tamil Nadu",
    "value": "9 M INR",
    "valueM": 9.0,
    "status": "Completed",
    "services": [
      "Air conditioning",
      "Chilled water piping",
      "Ducting",
      "Fire fighting",
      "Insulation",
      "Utility piping",
      "Ventilation"
    ],
    "industries": [
      "Automotive"
    ],
    "scopeServices": [],
    "image": "/images/projects/web/hitachi-ams.png",
    "featured": false,
    "epcPartner": "Hitachi plant technologies",
    "startYear": "2015",
    "endYear": "2016"
  },
  {
    "id": "ola-electric-giga-plant",
    "name": "OLA electric Giga plant",
    "city": "Krishnagiri",
    "state": "Tamil Nadu",
    "location": "Krishnagiri, Tamil Nadu",
    "value": "110 M INR",
    "valueM": 110.0,
    "status": "Completed",
    "services": [
      "Chilled water piping",
      "Ducting",
      "Insulation",
      "Ventilation"
    ],
    "industries": [
      "Clean room",
      "Lithium ion battery (Dry room)"
    ],
    "scopeServices": [],
    "image": "/images/projects/clean/ola-electric-giga-plant.jpg",
    "featured": false,
    "epcPartner": "Iclean",
    "startYear": "2023",
    "endYear": "2025"
  },
  {
    "id": "ola-electric-giga-plant-expansion",
    "name": "OLA electric Giga plant expansion",
    "city": "Krishnagiri",
    "state": "Tamil Nadu",
    "location": "Krishnagiri, Tamil Nadu",
    "value": "100 M INR",
    "valueM": 100.0,
    "status": "Ongoing",
    "services": [
      "Chilled water piping",
      "Ducting",
      "Insulation",
      "Ventilation"
    ],
    "industries": [
      "Clean room",
      "Lithium ion battery (Dry room)"
    ],
    "scopeServices": [],
    "image": "/images/projects/clean/ola-electric-giga-plant-expansion.jpg",
    "featured": true,
    "epcPartner": "Iclean",
    "startYear": "Ongoing"
  },
  {
    "id": "amara-raja-pilot-lab",
    "name": "Amara raja pilot lab",
    "city": "Hyderabad",
    "state": "Telangana",
    "location": "Hyderabad, Telangana",
    "value": "45 M INR",
    "valueM": 45.0,
    "status": "Completed",
    "services": [
      "Chilled water piping",
      "Ducting",
      "Insulation",
      "Ventilation"
    ],
    "industries": [
      "Clean room",
      "Lithium ion battery (Dry room)"
    ],
    "scopeServices": [],
    "image": "/images/projects/clean/amara-raja-pilot-lab.jpg",
    "featured": false,
    "epcPartner": "Iclean",
    "startYear": "2025",
    "endYear": "2026"
  },
  {
    "id": "amara-raja-giga-plant",
    "name": "Amara raja Giga plant",
    "city": "Hyderabad",
    "state": "Telangana",
    "location": "Hyderabad, Telangana",
    "value": "110 M INR",
    "valueM": 110.0,
    "status": "Ongoing",
    "services": [
      "Chilled water piping",
      "Ducting",
      "Insulation",
      "Ventilation"
    ],
    "industries": [
      "Clean room",
      "Lithium ion battery (Dry room)"
    ],
    "scopeServices": [],
    "image": "/images/projects/clean/amara-raja-giga-plant.jpg",
    "featured": true,
    "epcPartner": "Iclean",
    "startYear": "Ongoing"
  },
  {
    "id": "glaxo-smith-kline",
    "name": "Glaxo smith kline",
    "city": "Kolar",
    "state": "Karnataka",
    "location": "Kolar, Karnataka",
    "value": "6 M INR",
    "valueM": 6.0,
    "status": "Completed",
    "services": [
      "Chilled water piping",
      "Insulation"
    ],
    "industries": [
      "Pharmaceutical"
    ],
    "scopeServices": [],
    "image": "/images/projects/web/glaxo-smith-kline.png",
    "featured": false,
    "epcPartner": "Takasago thermal",
    "startYear": "2016",
    "endYear": "2018"
  },
  {
    "id": "glaxo-smith-kline-2",
    "name": "Glaxo smith kline",
    "city": "Kolar",
    "state": "Karnataka",
    "location": "Kolar, Karnataka",
    "value": "10 M INR",
    "valueM": 10.0,
    "status": "Completed",
    "services": [
      "Air conditioning",
      "Ducting",
      "Insulation",
      "Ventilation"
    ],
    "industries": [
      "Pharmaceutical"
    ],
    "scopeServices": [],
    "image": "/images/projects/web/glaxo-smith-kline-2.png",
    "featured": false,
    "epcPartner": "Shimizu corporation",
    "startYear": "2016",
    "endYear": "2018"
  },
  {
    "id": "imec",
    "name": "IMEC",
    "city": "Kolar",
    "state": "Karnataka",
    "location": "Kolar, Karnataka",
    "value": "11 M INR",
    "valueM": 11.0,
    "status": "Completed",
    "services": [
      "Air conditioning",
      "Ducting",
      "Insulation",
      "Ventilation"
    ],
    "industries": [
      "Other"
    ],
    "scopeServices": [],
    "image": "/images/projects/web/imec.png",
    "featured": false,
    "epcPartner": "Takenaka India",
    "startYear": "2016",
    "endYear": "2017"
  },
  {
    "id": "npri",
    "name": "NPRI",
    "city": "Malad",
    "state": "Karnataka",
    "location": "Malad, Karnataka",
    "value": "8 M INR",
    "valueM": 8.0,
    "status": "Completed",
    "services": [
      "Air conditioning",
      "Ducting",
      "Insulation",
      "Ventilation"
    ],
    "industries": [
      "Automotive"
    ],
    "scopeServices": [],
    "image": "/images/projects/web/npri.png",
    "featured": false,
    "epcPartner": "Takasago thermal",
    "startYear": "2016",
    "endYear": "2017"
  },
  {
    "id": "tokai-rika-minda",
    "name": "Tokai rika minda",
    "city": "Dabaspet",
    "state": "Karnataka",
    "location": "Dabaspet, Karnataka",
    "value": "25 M INR",
    "valueM": 25.0,
    "status": "Completed",
    "services": [
      "Air conditioning",
      "Chilled water piping",
      "Ducting",
      "Insulation",
      "Ventilation"
    ],
    "industries": [
      "Automotive"
    ],
    "scopeServices": [],
    "image": "/images/projects/web/tokai-rika-minda.png",
    "featured": false,
    "epcPartner": "Shimizu corporation",
    "startYear": "2017",
    "endYear": "2019"
  },
  {
    "id": "tmeic",
    "name": "TMEIC",
    "city": "Tumkur",
    "state": "Karnataka",
    "location": "Tumkur, Karnataka",
    "value": "10 M INR",
    "valueM": 10.0,
    "status": "Completed",
    "services": [
      "Air conditioning",
      "Ducting",
      "Fire fighting",
      "Insulation",
      "Utility piping",
      "Ventilation"
    ],
    "industries": [
      "Other"
    ],
    "scopeServices": [],
    "image": "/images/projects/web/tmeic.png",
    "featured": false,
    "epcPartner": "Takasago thermal",
    "startYear": "2016",
    "endYear": "2017"
  },
  {
    "id": "brother",
    "name": "Brother",
    "city": "Tumkur",
    "state": "Karnataka",
    "location": "Tumkur, Karnataka",
    "value": "20 M INR",
    "valueM": 20.0,
    "status": "Completed",
    "services": [
      "Fire fighting",
      "Utility piping"
    ],
    "industries": [
      "Other"
    ],
    "scopeServices": [],
    "image": "/images/projects/clean/brother.jpg",
    "featured": false,
    "epcPartner": "Shimizu corporation",
    "startYear": "2023",
    "endYear": "2024"
  },
  {
    "id": "aoyama",
    "name": "Aoyama",
    "city": "Tumkur",
    "state": "Karnataka",
    "location": "Tumkur, Karnataka",
    "value": "53 M INR",
    "valueM": 53.0,
    "status": "Ongoing",
    "services": [
      "Gas piping",
      "Steam piping",
      "Utility piping"
    ],
    "industries": [
      "Other"
    ],
    "scopeServices": [],
    "image": "/images/projects/clean/aoyama.jpg",
    "featured": false,
    "epcPartner": "Shimizu corporation",
    "startYear": "Ongoing"
  },
  {
    "id": "hcl-semiconductor-r-d",
    "name": "HCL semiconductor R&D",
    "city": "Bangalore",
    "state": "Karnataka",
    "location": "Bangalore, Karnataka",
    "value": "15 M INR",
    "valueM": 15.0,
    "status": "Completed",
    "services": [
      "Air conditioning",
      "Chilled water piping",
      "Ducting",
      "Gas piping",
      "Insulation",
      "Refrigeration",
      "Utility piping",
      "Ventilation"
    ],
    "industries": [
      "R&D"
    ],
    "scopeServices": [],
    "image": "/images/projects/clean/hcl-semiconductor-r-d.jpg",
    "featured": false,
    "epcPartner": "Nicomac",
    "startYear": "2024",
    "endYear": "2025"
  },
  {
    "id": "exide-energy",
    "name": "Exide energy",
    "city": "Devanhalli",
    "state": "Karnataka",
    "location": "Devanhalli, Karnataka",
    "value": "360 M INR",
    "valueM": 360.0,
    "status": "Completed",
    "services": [
      "Air conditioning",
      "Chilled water piping",
      "Ducting",
      "Dust collection",
      "Insulation",
      "Steam piping",
      "Utility piping",
      "Ventilation"
    ],
    "industries": [
      "Lithium ion battery (Dry room)"
    ],
    "scopeServices": [],
    "image": "/images/projects/clean/exide-energy.jpg",
    "featured": false,
    "epcPartner": "Iclean",
    "startYear": "2023",
    "endYear": "2026"
  },
  {
    "id": "infosys",
    "name": "Infosys",
    "city": "Bangalore",
    "state": "Karnataka",
    "location": "Bangalore, Karnataka",
    "value": "11 M INR",
    "valueM": 11.0,
    "status": "Completed",
    "services": [
      "Chilled water piping",
      "Insulation",
      "PEX piping",
      "Utility piping"
    ],
    "industries": [
      "office"
    ],
    "scopeServices": [],
    "image": "/images/projects/clean/infosys.jpg",
    "featured": false,
    "epcPartner": "Takasago thermal",
    "startYear": "2016",
    "endYear": "2017"
  },
  {
    "id": "mitsubishi-electric-fa",
    "name": "Mitsubishi electric - FA",
    "city": "Talegaon",
    "state": "Maharashtra",
    "location": "Talegaon, Maharashtra",
    "value": "40 M INR",
    "valueM": 40.0,
    "status": "Completed",
    "services": [
      "Ducting",
      "Fire fighting",
      "Insulation",
      "Utility piping",
      "Ventilation"
    ],
    "industries": [
      "Other"
    ],
    "scopeServices": [],
    "image": "/images/projects/clean/mitsubishi-electric-fa.jpg",
    "featured": false,
    "epcPartner": "Shimizu corporation",
    "startYear": "2023",
    "endYear": "2024"
  },
  {
    "id": "mitsubishi-electric-fa-2",
    "name": "Mitsubishi electric - FA",
    "city": "Talegaon",
    "state": "Maharashtra",
    "location": "Talegaon, Maharashtra",
    "value": "5 M INR",
    "valueM": 5.0,
    "status": "Completed",
    "services": [
      "Ducting",
      "Insulation",
      "Machine setup & hookup",
      "Utility piping"
    ],
    "industries": [
      "Other"
    ],
    "scopeServices": [],
    "image": "/images/projects/clean/mitsubishi-electric-fa-2.jpg",
    "featured": false,
    "epcPartner": "Mitsubishi electric FA",
    "startYear": "2023",
    "endYear": "2024"
  },
  {
    "id": "oyc-yeast",
    "name": "OYC - Yeast",
    "city": "Kesurdi",
    "state": "Maharashtra",
    "location": "Kesurdi, Maharashtra",
    "value": "1 M INR",
    "valueM": 1.0,
    "status": "Completed",
    "services": [
      "Ducting",
      "Insulation"
    ],
    "industries": [
      "Food"
    ],
    "scopeServices": [],
    "image": "/images/projects/clean/oyc-yeast.jpg",
    "featured": false,
    "epcPartner": "Shimizu corporation",
    "startYear": "2023",
    "endYear": "2023"
  },
  {
    "id": "toyota-boshuko",
    "name": "Toyota Boshuko",
    "city": "Sambhaji Nagar",
    "state": "Maharashtra",
    "location": "Sambhaji Nagar, Maharashtra",
    "value": "195 M INR",
    "valueM": 195.0,
    "status": "Ongoing",
    "services": [
      "Air conditioning",
      "Ducting",
      "Fire fighting",
      "Insulation",
      "Plumbing",
      "Utility piping",
      "Ventilation"
    ],
    "industries": [
      "Automotive"
    ],
    "scopeServices": [],
    "image": "/images/projects/clean/toyota-boshuko.jpg",
    "featured": true,
    "epcPartner": "Shimizu corporation",
    "startYear": "Ongoing"
  },
  {
    "id": "imax",
    "name": "IMAX",
    "city": "Mandal",
    "state": "Gujarat",
    "location": "Mandal, Gujarat",
    "value": "11 M INR",
    "valueM": 11.0,
    "status": "Completed",
    "services": [
      "Air conditioning",
      "Ducting",
      "Insulation",
      "Ventilation"
    ],
    "industries": [
      "Other"
    ],
    "scopeServices": [],
    "image": "/images/projects/web/imax.jpg",
    "featured": false,
    "epcPartner": "Takenaka India",
    "startYear": "2015",
    "endYear": "2016"
  },
  {
    "id": "ts-tech",
    "name": "TS tech",
    "city": "Mandal",
    "state": "Gujarat",
    "location": "Mandal, Gujarat",
    "value": "5 M INR",
    "valueM": 5.0,
    "status": "Completed",
    "services": [
      "Air conditioning",
      "Ducting",
      "Insulation",
      "Ventilation"
    ],
    "industries": [
      "Automotive"
    ],
    "scopeServices": [],
    "image": "/images/projects/web/ts-tech.png",
    "featured": false,
    "epcPartner": "Takenaka India",
    "startYear": "2015",
    "endYear": "2016"
  },
  {
    "id": "tdsg",
    "name": "TDSG",
    "city": "Becharaji",
    "state": "Gujarat",
    "location": "Becharaji, Gujarat",
    "value": "40 M INR",
    "valueM": 40.0,
    "status": "Completed",
    "services": [
      "Chilled water piping",
      "Ducting",
      "Dust collection",
      "Insulation",
      "Machine setup & hookup",
      "Utility piping",
      "Ventilation"
    ],
    "industries": [
      "Clean room",
      "Lithium ion battery (Dry room)"
    ],
    "scopeServices": [],
    "image": "/images/projects/clean/tdsg.jpg",
    "featured": false,
    "epcPartner": "Iclean",
    "startYear": "2018",
    "endYear": "2019"
  },
  {
    "id": "bnpa",
    "name": "BNPA",
    "city": "Anand",
    "state": "Gujarat",
    "location": "Anand, Gujarat",
    "value": "17 M INR",
    "valueM": 17.0,
    "status": "Completed",
    "services": [
      "Air conditioning",
      "Civil and interioirs",
      "Ducting",
      "Electrical",
      "Insulation",
      "Plumbing",
      "Utility piping",
      "Ventilation"
    ],
    "industries": [
      "Automotive"
    ],
    "scopeServices": [],
    "image": "/images/projects/clean/bnpa.jpg",
    "featured": false,
    "epcPartner": "DJK",
    "startYear": "2016",
    "endYear": "2017"
  },
  {
    "id": "futaba-expanion",
    "name": "Futaba Expanion",
    "city": "Becharaji",
    "state": "Gujarat",
    "location": "Becharaji, Gujarat",
    "value": "8 M INR",
    "valueM": 8.0,
    "status": "Completed",
    "services": [
      "Air conditioning",
      "Ducting",
      "Fire fighting",
      "Insulation",
      "Plumbing",
      "Utility piping",
      "Ventilation"
    ],
    "industries": [
      "Automotive"
    ],
    "scopeServices": [],
    "image": "/images/projects/clean/futaba-expanion.jpg",
    "featured": false,
    "epcPartner": "Takenaka India",
    "startYear": "2019",
    "endYear": "2019"
  },
  {
    "id": "mkci",
    "name": "MKCI",
    "city": "Sanand",
    "state": "Gujarat",
    "location": "Sanand, Gujarat",
    "value": "6 M INR",
    "valueM": 6.0,
    "status": "Completed",
    "services": [
      "Fire fighting",
      "Utility piping"
    ],
    "industries": [
      "Automotive"
    ],
    "scopeServices": [],
    "image": "/images/projects/clean/mkci.jpg",
    "featured": false,
    "epcPartner": "Takenaka India",
    "startYear": "2019",
    "endYear": "2019"
  },
  {
    "id": "oji-paper-2",
    "name": "OJI paper",
    "city": "Sanand",
    "state": "Gujarat",
    "location": "Sanand, Gujarat",
    "value": "25 M INR",
    "valueM": 25.0,
    "status": "Completed",
    "services": [
      "Fire fighting",
      "Gas piping",
      "Utility piping"
    ],
    "industries": [
      "Other"
    ],
    "scopeServices": [],
    "image": "/images/projects/clean/oji-paper-2.jpg",
    "featured": false,
    "epcPartner": "Takenaka India",
    "startYear": "2019",
    "endYear": "2020"
  },
  {
    "id": "ijl",
    "name": "IJL",
    "city": "Sanand",
    "state": "Gujarat",
    "location": "Sanand, Gujarat",
    "value": "70 M INR",
    "valueM": 70.0,
    "status": "Completed",
    "services": [
      "Air conditioning",
      "Chilled water piping",
      "Ducting",
      "Insulation",
      "Ventilation"
    ],
    "industries": [
      "Automotive"
    ],
    "scopeServices": [],
    "image": "/images/projects/clean/ijl.jpg",
    "featured": false,
    "epcPartner": "Takenaka India",
    "startYear": "2019",
    "endYear": "2020"
  },
  {
    "id": "fcc",
    "name": "FCC",
    "city": "Sanand",
    "state": "Gujarat",
    "location": "Sanand, Gujarat",
    "value": "12 M INR",
    "valueM": 12.0,
    "status": "Completed",
    "services": [
      "Ducting",
      "Insulation",
      "Ventilation"
    ],
    "industries": [
      "Automotive"
    ],
    "scopeServices": [],
    "image": "/images/projects/clean/fcc.jpg",
    "featured": false,
    "epcPartner": "Takenaka India",
    "startYear": "2019",
    "endYear": "2020"
  },
  {
    "id": "mitsubishi-a",
    "name": "Mitsubishi-A",
    "city": "Sanand",
    "state": "Gujarat",
    "location": "Sanand, Gujarat",
    "value": "22 M INR",
    "valueM": 22.0,
    "status": "Completed",
    "services": [
      "Ducting",
      "Insulation",
      "Ventilation"
    ],
    "industries": [],
    "scopeServices": [],
    "image": "/images/projects/clean/mitsubishi-a.jpg",
    "featured": false,
    "epcPartner": "Takenaka India",
    "startYear": "2020",
    "endYear": "2021"
  },
  {
    "id": "nifco",
    "name": "Nifco",
    "city": "Sanand",
    "state": "Gujarat",
    "location": "Sanand, Gujarat",
    "value": "2 M INR",
    "valueM": 2.0,
    "status": "Completed",
    "services": [
      "Chilled water piping",
      "Insulation",
      "Machine setup & hookup",
      "Utility piping"
    ],
    "industries": [
      "Automotive"
    ],
    "scopeServices": [],
    "image": "/images/projects/clean/nifco.jpg",
    "featured": false,
    "epcPartner": "DJK",
    "startYear": "2021",
    "endYear": "2022"
  },
  {
    "id": "unicharm-2",
    "name": "Unicharm",
    "city": "Sanand",
    "state": "Gujarat",
    "location": "Sanand, Gujarat",
    "value": "30 M INR",
    "valueM": 30.0,
    "status": "Completed",
    "services": [
      "Air conditioning",
      "Chilled water piping",
      "Ducting",
      "Dust collection",
      "Insulation",
      "Utility piping",
      "Ventilation"
    ],
    "industries": [
      "FMCG"
    ],
    "scopeServices": [],
    "image": "/images/projects/web/unicharm-2.png",
    "featured": false,
    "epcPartner": "Taikisha",
    "startYear": "2017",
    "endYear": "2019"
  },
  {
    "id": "hmsi-paint-shop",
    "name": "HMSI paint shop",
    "city": "Vithlapur",
    "state": "Gujarat",
    "location": "Vithlapur, Gujarat",
    "value": "15 M INR",
    "valueM": 15.0,
    "status": "Completed",
    "services": [
      "Chilled water piping",
      "Ducting",
      "Insulation",
      "Ventilation"
    ],
    "industries": [
      "Automotive"
    ],
    "scopeServices": [],
    "image": "/images/projects/clean/hmsi-paint-shop.jpg",
    "featured": false,
    "epcPartner": "DJK",
    "startYear": "2019",
    "endYear": "2020"
  },
  {
    "id": "tdsg-renovation",
    "name": "TDSG renovation",
    "city": "Becharaji",
    "state": "Gujarat",
    "location": "Becharaji, Gujarat",
    "value": "110 M INR",
    "valueM": 110.0,
    "status": "Completed",
    "services": [
      "Chilled water piping",
      "Ducting",
      "Dust collection",
      "Insulation",
      "Machine setup & hookup",
      "Utility piping",
      "Ventilation"
    ],
    "industries": [
      "Clean room",
      "Lithium ion battery (Dry room)"
    ],
    "scopeServices": [],
    "image": "/images/projects/clean/tdsg-renovation.jpg",
    "featured": false,
    "epcPartner": "Iclean",
    "startYear": "2022",
    "endYear": "2024"
  },
  {
    "id": "tdsg-anode-building",
    "name": "TDSG anode building",
    "city": "Becharaji",
    "state": "Gujarat",
    "location": "Becharaji, Gujarat",
    "value": "30 M INR",
    "valueM": 30.0,
    "status": "Completed",
    "services": [
      "Chilled water piping",
      "Ducting",
      "Dust collection",
      "Insulation",
      "Machine setup & hookup",
      "Utility piping",
      "Ventilation"
    ],
    "industries": [
      "Clean room",
      "Lithium ion battery (Dry room)"
    ],
    "scopeServices": [],
    "image": "/images/projects/clean/tdsg-anode-building.jpg",
    "featured": false,
    "epcPartner": "Iclean",
    "startYear": "2022",
    "endYear": "2024"
  },
  {
    "id": "tata-agratas",
    "name": "Tata Agratas",
    "city": "Sanand",
    "state": "Gujarat",
    "location": "Sanand, Gujarat",
    "value": "780 M INR",
    "valueM": 780.0,
    "status": "Ongoing",
    "services": [
      "Chilled water piping",
      "Ducting",
      "Insulation",
      "Steam piping",
      "Ventilation"
    ],
    "industries": [
      "Clean room",
      "Lithium ion battery (Dry room)"
    ],
    "scopeServices": [],
    "image": "/images/projects/clean/tata-agratas.jpg",
    "featured": true,
    "epcPartner": "Iclean",
    "startYear": "Ongoing"
  },
  {
    "id": "waree-giga-plant",
    "name": "Waree Giga plant",
    "city": "Valsad",
    "state": "Gujarat",
    "location": "Valsad, Gujarat",
    "value": "147 M INR",
    "valueM": 147.0,
    "status": "Ongoing",
    "services": [
      "Chilled water piping",
      "Ducting",
      "Insulation",
      "Steam piping",
      "Ventilation"
    ],
    "industries": [
      "Clean room",
      "Lithium ion battery (Dry room)"
    ],
    "scopeServices": [],
    "image": "/images/projects/clean/waree-giga-plant.jpg",
    "featured": true,
    "epcPartner": "Iclean",
    "startYear": "Ongoing"
  },
  {
    "id": "samsung-electronics",
    "name": "Samsung electronics",
    "city": "Noida",
    "state": "Uttar Pradesh",
    "location": "Noida, Uttar Pradesh",
    "value": "15 M INR",
    "valueM": 15.0,
    "status": "Completed",
    "services": [
      "Chilled water piping",
      "Insulation"
    ],
    "industries": [
      "Mobile phones"
    ],
    "scopeServices": [],
    "image": "/images/projects/web/samsung-electronics.png",
    "featured": false,
    "epcPartner": "Jungdo",
    "startYear": "2017",
    "endYear": "2018"
  },
  {
    "id": "bnpa-2",
    "name": "BNPA",
    "city": "Devla",
    "state": "Uttar Pradesh",
    "location": "Devla, Uttar Pradesh",
    "value": "80 M INR",
    "valueM": 80.0,
    "status": "Completed",
    "services": [
      "Air conditioning",
      "Chemical piping",
      "Chilled water piping",
      "Civil and interioirs",
      "Ducting",
      "Dust collection",
      "Electrical",
      "Gas piping",
      "Insulation",
      "Machine setup & hookup",
      "Plumbing",
      "Utility piping",
      "Ventilation"
    ],
    "industries": [
      "Automotive"
    ],
    "scopeServices": [],
    "image": "/images/projects/clean/bnpa-2.jpg",
    "featured": false,
    "epcPartner": "DJK",
    "startYear": "2018",
    "endYear": "2019"
  },
  {
    "id": "uil",
    "name": "UIL",
    "city": "Greater Noida",
    "state": "Uttar Pradesh",
    "location": "Greater Noida, Uttar Pradesh",
    "value": "7 M INR",
    "valueM": 7.0,
    "status": "Completed",
    "services": [
      "Ducting",
      "Insulation",
      "Ventilation"
    ],
    "industries": [
      "Mobile phones"
    ],
    "scopeServices": [],
    "image": "/images/projects/web/uil.png",
    "featured": false,
    "epcPartner": "Jeil Engineering",
    "startYear": "2017",
    "endYear": "2018"
  },
  {
    "id": "pepsico",
    "name": "Pepsico",
    "city": "Kosi Kala",
    "state": "Uttar Pradesh",
    "location": "Kosi Kala, Uttar Pradesh",
    "value": "55 M INR",
    "valueM": 55.0,
    "status": "Completed",
    "services": [
      "Plumbing",
      "Utility piping"
    ],
    "industries": [
      "Food"
    ],
    "scopeServices": [],
    "image": "/images/projects/clean/pepsico.jpg",
    "featured": false,
    "epcPartner": "Takenaka India",
    "startYear": "2020",
    "endYear": "2023"
  },
  {
    "id": "oiles",
    "name": "Oiles",
    "city": "Neemrana",
    "state": "Rajasthan",
    "location": "Neemrana, Rajasthan",
    "value": "88 M INR",
    "valueM": 88.0,
    "status": "Ongoing",
    "services": [
      "Ducting",
      "Fire fighting",
      "Insulation",
      "Utility piping",
      "Ventilation"
    ],
    "industries": [
      "Automotive"
    ],
    "scopeServices": [],
    "image": "/images/projects/clean/oiles.jpg",
    "featured": false,
    "epcPartner": "Takenaka India",
    "startYear": "Ongoing"
  },
  {
    "id": "ts-tech-2",
    "name": "TS tech",
    "city": "Neemrana",
    "state": "Rajasthan",
    "location": "Neemrana, Rajasthan",
    "value": "35 M INR",
    "valueM": 35.0,
    "status": "Completed",
    "services": [
      "Fire fighting",
      "Gas piping",
      "Utility piping"
    ],
    "industries": [
      "Automotive"
    ],
    "scopeServices": [],
    "image": "/images/projects/web/ts-tech-2.png",
    "featured": false,
    "epcPartner": "Takenaka India",
    "startYear": "2025",
    "endYear": "2025"
  },
  {
    "id": "daikin-jiim",
    "name": "Daikin JIIM",
    "city": "Neemrana",
    "state": "Rajasthan",
    "location": "Neemrana, Rajasthan",
    "value": "10 M INR",
    "valueM": 10.0,
    "status": "Completed",
    "services": [
      "Ducting",
      "Fire fighting",
      "Insulation",
      "Utility piping",
      "Ventilation"
    ],
    "industries": [
      "Air conditioning"
    ],
    "scopeServices": [],
    "image": "/images/projects/clean/daikin-jiim.jpg",
    "featured": false,
    "epcPartner": "Takenaka India",
    "startYear": "2025",
    "endYear": "2025"
  },
  {
    "id": "tokai-rika-minda-2",
    "name": "Tokai rika minda",
    "city": "Neemrana",
    "state": "Rajasthan",
    "location": "Neemrana, Rajasthan",
    "value": "75 M INR",
    "valueM": 75.0,
    "status": "Completed",
    "services": [
      "Chilled water piping",
      "DG Chimey",
      "Ducting",
      "Fire fighting",
      "Insulation",
      "Utility piping",
      "Ventilation"
    ],
    "industries": [
      "Automotive"
    ],
    "scopeServices": [],
    "image": "/images/projects/web/tokai-rika-minda-2.png",
    "featured": false,
    "epcPartner": "Takenaka India",
    "startYear": "2023",
    "endYear": "2024"
  },
  {
    "id": "daikin-r-d",
    "name": "Daikin R&D",
    "city": "Neemrana",
    "state": "Rajasthan",
    "location": "Neemrana, Rajasthan",
    "value": "25 M INR",
    "valueM": 25.0,
    "status": "Completed",
    "services": [
      "DG Chimey",
      "Fire fighting",
      "Gas piping",
      "Utility piping"
    ],
    "industries": [
      "Air conditioning"
    ],
    "scopeServices": [],
    "image": "/images/projects/web/daikin-r-d.png",
    "featured": false,
    "epcPartner": "Takenaka India",
    "startYear": "2022",
    "endYear": "2024"
  },
  {
    "id": "tsk",
    "name": "TSK",
    "city": "Neemrana",
    "state": "Rajasthan",
    "location": "Neemrana, Rajasthan",
    "value": "5 M INR",
    "valueM": 5.0,
    "status": "Completed",
    "services": [
      "Air conditioning",
      "DG Chimey",
      "Ducting",
      "Electrical",
      "Fire fighting",
      "Insulation",
      "Utility piping",
      "Ventilation"
    ],
    "industries": [
      "Automotive"
    ],
    "scopeServices": [],
    "image": "/images/projects/clean/tsk.jpg",
    "featured": false,
    "epcPartner": "Rajiv associates",
    "startYear": "2025",
    "endYear": "2026"
  },
  {
    "id": "nissin-brake",
    "name": "Nissin brake",
    "city": "Neemrana",
    "state": "Rajasthan",
    "location": "Neemrana, Rajasthan",
    "value": "5 M INR",
    "valueM": 5.0,
    "status": "Completed",
    "services": [
      "Ducting",
      "Insulation",
      "Ventilation"
    ],
    "industries": [
      "Automotive"
    ],
    "scopeServices": [],
    "image": "/images/projects/clean/nissin-brake.jpg",
    "featured": false,
    "epcPartner": "SMCC",
    "startYear": "2017",
    "endYear": "2017"
  },
  {
    "id": "hitachi-astemo",
    "name": "Hitachi astemo",
    "city": "Neemrana",
    "state": "Rajasthan",
    "location": "Neemrana, Rajasthan",
    "value": "15 M INR",
    "valueM": 15.0,
    "status": "Completed",
    "services": [
      "Ducting",
      "Insulation",
      "Machine setup & hookup",
      "Utility piping",
      "Ventilation"
    ],
    "industries": [
      "Automotive"
    ],
    "scopeServices": [],
    "image": "/images/projects/clean/hitachi-astemo.jpg",
    "featured": false,
    "epcPartner": "SMCC",
    "startYear": "2019",
    "endYear": "2020"
  },
  {
    "id": "e-h",
    "name": "E&H",
    "city": "Neemrana",
    "state": "Rajasthan",
    "location": "Neemrana, Rajasthan",
    "value": "14 M INR",
    "valueM": 14.0,
    "status": "Completed",
    "services": [
      "Air conditioning",
      "Ducting",
      "Fire fighting",
      "Insulation",
      "Utility piping",
      "Ventilation"
    ],
    "industries": [
      "Automotive"
    ],
    "scopeServices": [],
    "image": "/images/projects/clean/e-h.jpg",
    "featured": false,
    "epcPartner": "SMCC",
    "startYear": "2017",
    "endYear": "2018"
  },
  {
    "id": "nihon-parker",
    "name": "Nihon parker",
    "city": "Neemrana",
    "state": "Rajasthan",
    "location": "Neemrana, Rajasthan",
    "value": "12 M INR",
    "valueM": 12.0,
    "status": "Completed",
    "services": [
      "Air conditioning",
      "Ducting",
      "Fire fighting",
      "Insulation",
      "Utility piping",
      "Ventilation"
    ],
    "industries": [
      "Other"
    ],
    "scopeServices": [],
    "image": "/images/projects/web/nihon-parker.png",
    "featured": false,
    "epcPartner": "SMCC",
    "startYear": "2017",
    "endYear": "2017"
  },
  {
    "id": "nippon-express",
    "name": "Nippon express",
    "city": "Neemrana",
    "state": "Rajasthan",
    "location": "Neemrana, Rajasthan",
    "value": "8 M INR",
    "valueM": 8.0,
    "status": "Completed",
    "services": [
      "Air conditioning",
      "Ducting",
      "Fire fighting",
      "Insulation",
      "Utility piping",
      "Ventilation"
    ],
    "industries": [
      "Other"
    ],
    "scopeServices": [],
    "image": "/images/projects/clean/nippon-express.jpg",
    "featured": false,
    "epcPartner": "SMCC",
    "startYear": "2017",
    "endYear": "2017"
  },
  {
    "id": "daido",
    "name": "Daido",
    "city": "Neemrana",
    "state": "Rajasthan",
    "location": "Neemrana, Rajasthan",
    "value": "6 M INR",
    "valueM": 6.0,
    "status": "Completed",
    "services": [
      "Air conditioning",
      "Ducting",
      "Fire fighting",
      "Insulation",
      "Utility piping",
      "Ventilation"
    ],
    "industries": [
      "Other"
    ],
    "scopeServices": [],
    "image": "/images/projects/clean/daido.jpg",
    "featured": false,
    "epcPartner": "SMCC",
    "startYear": "2017",
    "endYear": "2017"
  },
  {
    "id": "jtekt",
    "name": "JTEKT",
    "city": "Dharuhera",
    "state": "Rajasthan",
    "location": "Dharuhera, Rajasthan",
    "value": "13 M INR",
    "valueM": 13.0,
    "status": "Completed",
    "services": [
      "Fire fighting"
    ],
    "industries": [
      "Automotive"
    ],
    "scopeServices": [],
    "image": "/images/projects/clean/jtekt.jpg",
    "featured": false,
    "epcPartner": "Takenaka India",
    "startYear": "2025",
    "endYear": "2026"
  },
  {
    "id": "maruti-suzuki-r-d",
    "name": "Maruti suzuki R&D",
    "city": "Rohtak",
    "state": "Haryana",
    "location": "Rohtak, Haryana",
    "value": "270 M INR",
    "valueM": 270.0,
    "status": "Ongoing",
    "services": [
      "Air conditioning",
      "Civil and interioirs",
      "Ducting",
      "Electrical",
      "Fire fighting",
      "Gas piping",
      "Insulation",
      "Machine setup & hookup",
      "Refrigeration",
      "Steam piping",
      "Turnkey AWC lab",
      "Utility piping",
      "Ventilation"
    ],
    "industries": [
      "Automotive",
      "R&D"
    ],
    "scopeServices": [],
    "image": "/images/projects/clean/maruti-suzuki-r-d.jpg",
    "featured": true,
    "startYear": "Ongoing"
  },
  {
    "id": "bellsonica",
    "name": "Bellsonica",
    "city": "Kharkhoda",
    "state": "Haryana",
    "location": "Kharkhoda, Haryana",
    "value": "70 M INR",
    "valueM": 70.0,
    "status": "Completed",
    "services": [
      "Air conditioning",
      "DG Chimey",
      "Ducting",
      "Insulation",
      "Plumbing",
      "Utility piping",
      "Ventilation"
    ],
    "industries": [
      "Automotive"
    ],
    "scopeServices": [],
    "image": "/images/projects/clean/bellsonica.jpg",
    "featured": false,
    "epcPartner": "Takenaka India",
    "startYear": "2024",
    "endYear": "2025"
  },
  {
    "id": "suzuki-motorcycles",
    "name": "Suzuki motorcycles",
    "city": "Kharkhoda",
    "state": "Haryana",
    "location": "Kharkhoda, Haryana",
    "value": "68 M INR",
    "valueM": 68.0,
    "status": "Ongoing",
    "services": [
      "Fire fighting",
      "Utility piping"
    ],
    "industries": [
      "Automotive"
    ],
    "scopeServices": [],
    "image": "/images/projects/clean/suzuki-motorcycles.jpg",
    "featured": false,
    "epcPartner": "Takenaka India",
    "startYear": "Ongoing"
  },
  {
    "id": "ykk",
    "name": "YKK",
    "city": "Bawal",
    "state": "Haryana",
    "location": "Bawal, Haryana",
    "value": "23 M INR",
    "valueM": 23.0,
    "status": "Ongoing",
    "services": [
      "Air conditioning",
      "Ducting",
      "Insulation",
      "Ventilation"
    ],
    "industries": [
      "Other"
    ],
    "scopeServices": [],
    "image": "/images/projects/clean/ykk.jpg",
    "featured": false,
    "epcPartner": "DJK",
    "startYear": "Ongoing"
  },
  {
    "id": "ykk-2",
    "name": "YKK",
    "city": "Bawal",
    "state": "Haryana",
    "location": "Bawal, Haryana",
    "value": "70 M INR",
    "valueM": 70.0,
    "status": "Completed",
    "services": [
      "Fire fighting"
    ],
    "industries": [
      "Other"
    ],
    "scopeServices": [],
    "image": "/images/projects/clean/ykk-2.jpg",
    "featured": false,
    "epcPartner": "Takenaka India",
    "startYear": "2017",
    "endYear": "2018"
  },
  {
    "id": "acti",
    "name": "ACTI",
    "city": "Binola",
    "state": "Haryana",
    "location": "Binola, Haryana",
    "value": "22 M INR",
    "valueM": 22.0,
    "status": "Completed",
    "services": [
      "Air conditioning",
      "Civil and interioirs",
      "DG Chimey",
      "Ducting",
      "Electrical",
      "Insulation",
      "Machine setup & hookup",
      "Plumbing",
      "Utility piping",
      "Ventilation"
    ],
    "industries": [
      "Automotive"
    ],
    "scopeServices": [],
    "image": "/images/projects/clean/acti.jpg",
    "featured": false,
    "epcPartner": "DJK",
    "startYear": "2017",
    "endYear": "2017"
  },
  {
    "id": "denso",
    "name": "Denso",
    "city": "Manesar",
    "state": "Haryana",
    "location": "Manesar, Haryana",
    "value": "7 M INR",
    "valueM": 7.0,
    "status": "Completed",
    "services": [
      "Electrical",
      "Machine setup & hookup",
      "Utility piping"
    ],
    "industries": [
      "Automotive"
    ],
    "scopeServices": [],
    "image": "/images/projects/clean/denso.jpg",
    "featured": false,
    "epcPartner": "DJK",
    "startYear": "2020",
    "endYear": "2020"
  },
  {
    "id": "denso-2",
    "name": "Denso",
    "city": "Manesar",
    "state": "Haryana",
    "location": "Manesar, Haryana",
    "value": "12 M INR",
    "valueM": 12.0,
    "status": "Completed",
    "services": [
      "Air conditioning",
      "Chilled water piping",
      "Ducting",
      "Dust collection",
      "Insulation",
      "Machine setup & hookup",
      "Refrigeration",
      "Steam piping",
      "Utility piping",
      "Ventilation"
    ],
    "industries": [
      "Automotive",
      "R&D"
    ],
    "scopeServices": [],
    "image": "/images/projects/clean/denso-2.jpg",
    "featured": false,
    "epcPartner": "Taikisha",
    "startYear": "2020",
    "endYear": "2021"
  },
  {
    "id": "plastic-omnium",
    "name": "Plastic omnium",
    "city": "Manesar",
    "state": "Haryana",
    "location": "Manesar, Haryana",
    "value": "9 M INR",
    "valueM": 9.0,
    "status": "Completed",
    "services": [
      "Chilled water piping",
      "Ducting",
      "Utility piping",
      "Ventilation"
    ],
    "industries": [
      "Automotive"
    ],
    "scopeServices": [],
    "image": "/images/projects/clean/plastic-omnium.jpg",
    "featured": false,
    "epcPartner": "Takenaka India",
    "startYear": "2016",
    "endYear": "2017"
  },
  {
    "id": "doosan",
    "name": "Doosan",
    "city": "Gurugram",
    "state": "Haryana",
    "location": "Gurugram, Haryana",
    "value": "2 M INR",
    "valueM": 2.0,
    "status": "Completed",
    "services": [
      "Air conditioning",
      "Chilled water piping",
      "Ducting",
      "Insulation",
      "Ventilation"
    ],
    "industries": [
      "office"
    ],
    "scopeServices": [],
    "image": "/images/projects/clean/doosan.jpg",
    "featured": false,
    "epcPartner": "Hankuk",
    "startYear": "2016",
    "endYear": "2017"
  },
  {
    "id": "shilla",
    "name": "Shilla",
    "city": "Gurugram",
    "state": "Haryana",
    "location": "Gurugram, Haryana",
    "value": "2 M INR",
    "valueM": 2.0,
    "status": "Completed",
    "services": [
      "Air conditioning",
      "Chilled water piping",
      "Ducting",
      "Insulation",
      "Ventilation"
    ],
    "industries": [
      "office"
    ],
    "scopeServices": [],
    "image": "/images/projects/clean/shilla.jpg",
    "featured": false,
    "epcPartner": "Hankuk",
    "startYear": "2024",
    "endYear": "2024"
  }
];

export type { Project };
